### ISSUE TITLE
Dataset tab "Begin Process" button - Certificate verify failed

### ISSUE THREAD

**Issue by TomiVolt** [JarodMica/beatrice_trainer_webui#2]
Hi Jarod, fresh install of win 10 and ran into a different issue, here is the console info - thanks for any advice:

C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0>runtime\python.exe webui.py
C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
No language specified, language will be first be detected for each audio file (increases inference time).
Non float16 compatible GPU: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
No language specified, language will be first be detected for each audio file (increases inference time).
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1303, in request
  File "http\client.py", line 1349, in _send_request
  File "http\client.py", line 1298, in endheaders
  File "http\client.py", line 1058, in _send_output
  File "http\client.py", line 996, in send
  File "http\client.py", line 1475, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\webui.py", line 61, in load_whisperx
    whisper_model = whisperx.load_model(model_name, device, download_root="whisper_models", compute_type="float16")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\whisperx\vad.py", line 29, in load_vad_model
    with urllib.request.urlopen(VAD_SEGMENTATION_URL) as source, open(model_fp, "wb") as output:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1303, in request
  File "http\client.py", line 1349, in _send_request
  File "http\client.py", line 1298, in endheaders
  File "http\client.py", line 1058, in _send_output
  File "http\client.py", line 996, in send
  File "http\client.py", line 1475, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1104, in _create
  File "ssl.py", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\webui.py", line 146, in process_proxy
    whisper_model = load_whisperx('large-v3')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\webui.py", line 64, in load_whisperx
    whisper_model = whisperx.load_model(model_name, device, download_root="whisper_models", compute_type="int8")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\whisperx\asr.py", line 347, in load_model
    vad_model = load_vad_model(torch.device(device), use_auth_token=None, **default_vad_options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tuvok\Desktop\beatrice_trainer_webui_v1.0\runtime\Lib\site-packages\whisperx\vad.py", line 29, in load_vad_model
    with urllib.request.urlopen(VAD_SEGMENTATION_URL) as source, open(model_fp, "wb") as output:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

**Comment by TomiVolt** [comment]
Tried to update my trusted certs but no luck:  pip install --upgrade certifi
