### ISSUE TITLE
gradio.exceptions.Error: RuntimeError('Repository root is not found.')

### ISSUE THREAD

**Issue by yukiarimo** [JarodMica/beatrice_trainer_webui#3]
Doesn't work

**Comment by JarodMica** [comment]
What method of installation did you use, manual or package? There needs to a folder named .git in the root directory

**Comment by HotshotGT** [comment]
Getting the same error with a manual install when I try to start training. I have a .git folder in the root directory.

For some context, I had to downgrade numpy to 1.26.4 to get the webui to load, and I had to install cudnn via conda for whisper to load properly and finish processing my dataset to even get this far.

<details>
<summary>Here's the actual output</summary>

```
[<gradio.components.dropdown.Dropdown object at 0x00000188E46DCE10>]
device=cuda
config:
{'adam_betas': [0.8, 0.99],
 'adam_eps': 1e-06,
 'batch_size': 16,
 'grad_balancer_ema_decay': 0.995,
 'grad_weight_adv': 1.0,
 'grad_weight_fm': 1.0,
 'grad_weight_mel': 1.0,
 'hidden_channels': 256,
 'in_ir_wav_dir': 'assets/ir',
 'in_noise_wav_dir': 'assets/noise',
 'in_sample_rate': 16000,
 'in_test_wav_dir': 'assets/test',
 'learning_rate': 0.0001,
 'min_learning_rate': 5e-06,
 'n_steps': 60,
 'num_workers': 4,
 'out_sample_rate': 24000,
 'phone_extractor_file': 'assets/pretrained/003b_checkpoint_03000000.pt',
 'pitch_estimator_file': 'assets/pretrained/008_1_checkpoint_00300000.pt',
 'pretrained_file': 'assets/pretrained/040c_checkpoint_libritts_r_200_02300000.pt',
 'san': False,
 'segment_length': 100,
 'use_amp': True,
 'warmup_steps': 30,
 'wav_length': 96000}

Traceback (most recent call last):
  File "C:\Python\beatrice_trainer_webui\webui.py", line 267, in training_proxy
    run_training(data_dir, models_output_dir, batches_per_epoch, save_interval, log_interval , resume, updated_config_path)
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\beatrice_trainer\src\train.py", line 430, in run_training
    ) = prepare_training(data_dir, out_dir, resume, config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\beatrice_trainer\src\train.py", line 79, in prepare_training
    in_ir_wav_dir = repo_root() / h.in_ir_wav_dir
                    ^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\beatrice_trainer\src\utils.py", line 87, in repo_root
    raise RuntimeError("Repository root is not found.")
RuntimeError: Repository root is not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python\miniconda3\envs\Beatrice\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python\beatrice_trainer_webui\webui.py", line 269, in training_proxy
    raise gr.Error(e)
gradio.exceptions.Error: RuntimeError('Repository root is not found.')
```

</details>

**Comment by yukiarimo** [comment]
Beatrice is unusable. Closing as not needed

**Comment by Docteur-RS** [comment]
For people who want to bang their head on to the next bug I've got a crappy solution for you.

The `repo_root()` method searches for a `.git` folder from bottom to top. However, if you have used conda then the library that executes the `repo_root()` method is probably located outside the git projet. For instance in my stacktrace I can see that the file in question is in the miniconda folder: `/home/ubuntu/miniconda3/envs/bea/lib/python3.11/site-packages/beatrice_trainer/src/utils.py`. So it's nowhere near the beatrice root repo.

So.... A quick fix would be to edit the utils file and tell the damn thing WHERE the root repo trully is.

By default the method looks like this:
```
def repo_root() -> Path:
    # d = Path.cwd() / "dummy" if is_notebook() else Path(__file__)
    d = Path(__file__)
    assert d.is_absolute(), d
    for d in d.parents:
        if (d / ".git").is_dir():
            return d
    raise RuntimeError("Repository root is not found.")
```

Change it to return the actual path of your root repo:
```
def repo_root() -> Path:
    return Path('/home/ubuntu/real_time/training/beatrice_trainer_webui')
```

There you go. Crappy AF. But it's working.  
On to the next bug now. Yolo.

---

Also, if this has helped you in any way, consider giving a star to my favorite Github repository: [https://github.com/rememberSoftwares/yacana/](https://github.com/rememberSoftwares/yacana/). Opensource needs help ;-)
